language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
addons:
  apt:
    packages:
      - ant-contrib
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIA1234567890
    - AWS_SECRET_ACCESS_KEY=AKIA1234567890

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction
  - dpkg -s ant-contrib
  - ant prepare

script:
  - ant
