language: php

php:
  - 5.5
  - 5.6
  - 7.0

addons:
  apt:
    packages:
      - ant-contrib

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction
  - dpkg -s ant-contrib
  - ant prepare

script:
  - ant
